# Generated by Django 4.2.4 on 2023-09-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_book_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_artist',
            name='artist_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book_artist',
            name='pyment_status',
            field=models.BooleanField(default=False),
        ),
    ]
