# Generated by Django 4.2.4 on 2023-09-14 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_book_artist_artist_confirmation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_artist',
            old_name='pyment_status',
            new_name='payment_status',
        ),
    ]
